SELECT S.FOOD_TYPE, REST_ID, REST_NAME, I.FAVORITES
FROM REST_INFO I
JOIN (SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
    FROM REST_INFO 
    GROUP BY FOOD_TYPE) S
    ON I.FAVORITES = S.FAVORITES
GROUP BY FOOD_TYPE
ORDER BY FOOD_TYPE DESC