SELECT ID, EMAIL, FIRST_NAME, LAST_NAME
FROM DEVELOPERS 
WHERE (SELECT CODE FROM SKILLCODES WHERE NAME='PYTHON') & SKILL_CODE != 0
    OR (SELECT CODE FROM SKILLCODES WHERE NAME='C#') & SKILL_CODE != 0
ORDER BY ID