SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR
    , S.MAX - E.SIZE_OF_COLONY AS YEAR_DEV
    , ID
FROM ECOLI_DATA E
JOIN (SELECT YEAR(DIFFERENTIATION_DATE) AS YEAR, MAX(SIZE_OF_COLONY) AS MAX
      FROM ECOLI_DATA
      GROUP BY YEAR(DIFFERENTIATION_DATE)) S
      ON YEAR(E.DIFFERENTIATION_DATE) = S.YEAR
ORDER BY YEAR, YEAR_DEV