SELECT DISTINCT R.CAR_ID
FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY R
LEFT JOIN CAR_RENTAL_COMPANY_CAR C ON C.CAR_ID = R.CAR_ID
WHERE MONTH(START_DATE) = 10 
    AND CAR_TYPE = '세단'
ORDER BY R.CAR_ID DESC