SELECT B.TITLE, B.BOARD_ID, D.REPLY_ID, D.WRITER_ID, D.CONTENTS, DATE_FORMAT(D.CREATED_DATE, '%Y-%m-%d') AS CREATED_DATE
FROM USED_GOODS_BOARD B
JOIN USED_GOODS_REPLY D ON B.BOARD_ID = D.BOARD_ID
WHERE B.CREATED_DATE >= '2022-10-01'
    AND B.CREATED_DATE < '2022-11-01'
ORDER BY D.CREATED_DATE ASC, TITLE ASC